branch-defaults:
  default:
    environment: pixselleyeApp-env
global:
  application_name: pixselleye-app
  default_ec2_keyname: pixselleye-keypair
  default_platform: 64bit Amazon Linux 2015.03 v1.3.2 running PHP 5.6
  default_region: ap-southeast-1
  profile: eb-cli
  sc: null
